// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActualizarPrecios.proto

package grpc;

public final class ActualizarPreciosProto {
  private ActualizarPreciosProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ActualizarRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActualizarRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string NIF = 1;</code>
     */
    java.lang.String getNIF();
    /**
     * <code>string NIF = 1;</code>
     */
    com.google.protobuf.ByteString
        getNIFBytes();

    /**
     * <code>string Apellidos = 2;</code>
     */
    java.lang.String getApellidos();
    /**
     * <code>string Apellidos = 2;</code>
     */
    com.google.protobuf.ByteString
        getApellidosBytes();

    /**
     * <code>string IP = 3;</code>
     */
    java.lang.String getIP();
    /**
     * <code>string IP = 3;</code>
     */
    com.google.protobuf.ByteString
        getIPBytes();
  }
  /**
   * Protobuf type {@code ActualizarRequest}
   */
  public  static final class ActualizarRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActualizarRequest)
      ActualizarRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActualizarRequest.newBuilder() to construct.
    private ActualizarRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActualizarRequest() {
      nIF_ = "";
      apellidos_ = "";
      iP_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActualizarRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nIF_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              apellidos_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              iP_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ActualizarPreciosProto.internal_static_ActualizarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ActualizarPreciosProto.internal_static_ActualizarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ActualizarPreciosProto.ActualizarRequest.class, grpc.ActualizarPreciosProto.ActualizarRequest.Builder.class);
    }

    public static final int NIF_FIELD_NUMBER = 1;
    private volatile java.lang.Object nIF_;
    /**
     * <code>string NIF = 1;</code>
     */
    public java.lang.String getNIF() {
      java.lang.Object ref = nIF_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nIF_ = s;
        return s;
      }
    }
    /**
     * <code>string NIF = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNIFBytes() {
      java.lang.Object ref = nIF_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nIF_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APELLIDOS_FIELD_NUMBER = 2;
    private volatile java.lang.Object apellidos_;
    /**
     * <code>string Apellidos = 2;</code>
     */
    public java.lang.String getApellidos() {
      java.lang.Object ref = apellidos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apellidos_ = s;
        return s;
      }
    }
    /**
     * <code>string Apellidos = 2;</code>
     */
    public com.google.protobuf.ByteString
        getApellidosBytes() {
      java.lang.Object ref = apellidos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apellidos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object iP_;
    /**
     * <code>string IP = 3;</code>
     */
    public java.lang.String getIP() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      }
    }
    /**
     * <code>string IP = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      java.lang.Object ref = iP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNIFBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nIF_);
      }
      if (!getApellidosBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, apellidos_);
      }
      if (!getIPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iP_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNIFBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nIF_);
      }
      if (!getApellidosBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, apellidos_);
      }
      if (!getIPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iP_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ActualizarPreciosProto.ActualizarRequest)) {
        return super.equals(obj);
      }
      grpc.ActualizarPreciosProto.ActualizarRequest other = (grpc.ActualizarPreciosProto.ActualizarRequest) obj;

      boolean result = true;
      result = result && getNIF()
          .equals(other.getNIF());
      result = result && getApellidos()
          .equals(other.getApellidos());
      result = result && getIP()
          .equals(other.getIP());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NIF_FIELD_NUMBER;
      hash = (53 * hash) + getNIF().hashCode();
      hash = (37 * hash) + APELLIDOS_FIELD_NUMBER;
      hash = (53 * hash) + getApellidos().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIP().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ActualizarPreciosProto.ActualizarRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActualizarRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActualizarRequest)
        grpc.ActualizarPreciosProto.ActualizarRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ActualizarPreciosProto.ActualizarRequest.class, grpc.ActualizarPreciosProto.ActualizarRequest.Builder.class);
      }

      // Construct using grpc.ActualizarPreciosProto.ActualizarRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nIF_ = "";

        apellidos_ = "";

        iP_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarRequest_descriptor;
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarRequest getDefaultInstanceForType() {
        return grpc.ActualizarPreciosProto.ActualizarRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarRequest build() {
        grpc.ActualizarPreciosProto.ActualizarRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarRequest buildPartial() {
        grpc.ActualizarPreciosProto.ActualizarRequest result = new grpc.ActualizarPreciosProto.ActualizarRequest(this);
        result.nIF_ = nIF_;
        result.apellidos_ = apellidos_;
        result.iP_ = iP_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ActualizarPreciosProto.ActualizarRequest) {
          return mergeFrom((grpc.ActualizarPreciosProto.ActualizarRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ActualizarPreciosProto.ActualizarRequest other) {
        if (other == grpc.ActualizarPreciosProto.ActualizarRequest.getDefaultInstance()) return this;
        if (!other.getNIF().isEmpty()) {
          nIF_ = other.nIF_;
          onChanged();
        }
        if (!other.getApellidos().isEmpty()) {
          apellidos_ = other.apellidos_;
          onChanged();
        }
        if (!other.getIP().isEmpty()) {
          iP_ = other.iP_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ActualizarPreciosProto.ActualizarRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ActualizarPreciosProto.ActualizarRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nIF_ = "";
      /**
       * <code>string NIF = 1;</code>
       */
      public java.lang.String getNIF() {
        java.lang.Object ref = nIF_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nIF_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string NIF = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNIFBytes() {
        java.lang.Object ref = nIF_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nIF_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string NIF = 1;</code>
       */
      public Builder setNIF(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nIF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string NIF = 1;</code>
       */
      public Builder clearNIF() {
        
        nIF_ = getDefaultInstance().getNIF();
        onChanged();
        return this;
      }
      /**
       * <code>string NIF = 1;</code>
       */
      public Builder setNIFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nIF_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apellidos_ = "";
      /**
       * <code>string Apellidos = 2;</code>
       */
      public java.lang.String getApellidos() {
        java.lang.Object ref = apellidos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apellidos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Apellidos = 2;</code>
       */
      public com.google.protobuf.ByteString
          getApellidosBytes() {
        java.lang.Object ref = apellidos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apellidos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Apellidos = 2;</code>
       */
      public Builder setApellidos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apellidos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Apellidos = 2;</code>
       */
      public Builder clearApellidos() {
        
        apellidos_ = getDefaultInstance().getApellidos();
        onChanged();
        return this;
      }
      /**
       * <code>string Apellidos = 2;</code>
       */
      public Builder setApellidosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apellidos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iP_ = "";
      /**
       * <code>string IP = 3;</code>
       */
      public java.lang.String getIP() {
        java.lang.Object ref = iP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string IP = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIPBytes() {
        java.lang.Object ref = iP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IP = 3;</code>
       */
      public Builder setIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IP = 3;</code>
       */
      public Builder clearIP() {
        
        iP_ = getDefaultInstance().getIP();
        onChanged();
        return this;
      }
      /**
       * <code>string IP = 3;</code>
       */
      public Builder setIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iP_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActualizarRequest)
    }

    // @@protoc_insertion_point(class_scope:ActualizarRequest)
    private static final grpc.ActualizarPreciosProto.ActualizarRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ActualizarPreciosProto.ActualizarRequest();
    }

    public static grpc.ActualizarPreciosProto.ActualizarRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActualizarRequest>
        PARSER = new com.google.protobuf.AbstractParser<ActualizarRequest>() {
      @java.lang.Override
      public ActualizarRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActualizarRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActualizarRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActualizarRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ActualizarPreciosProto.ActualizarRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActualizarReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActualizarReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tipoDemanda = 1;</code>
     */
    java.lang.String getTipoDemanda();
    /**
     * <code>string tipoDemanda = 1;</code>
     */
    com.google.protobuf.ByteString
        getTipoDemandaBytes();

    /**
     * <code>double precio = 2;</code>
     */
    double getPrecio();
  }
  /**
   * Protobuf type {@code ActualizarReply}
   */
  public  static final class ActualizarReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActualizarReply)
      ActualizarReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActualizarReply.newBuilder() to construct.
    private ActualizarReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActualizarReply() {
      tipoDemanda_ = "";
      precio_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActualizarReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tipoDemanda_ = s;
              break;
            }
            case 17: {

              precio_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ActualizarPreciosProto.internal_static_ActualizarReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ActualizarPreciosProto.internal_static_ActualizarReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ActualizarPreciosProto.ActualizarReply.class, grpc.ActualizarPreciosProto.ActualizarReply.Builder.class);
    }

    public static final int TIPODEMANDA_FIELD_NUMBER = 1;
    private volatile java.lang.Object tipoDemanda_;
    /**
     * <code>string tipoDemanda = 1;</code>
     */
    public java.lang.String getTipoDemanda() {
      java.lang.Object ref = tipoDemanda_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipoDemanda_ = s;
        return s;
      }
    }
    /**
     * <code>string tipoDemanda = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTipoDemandaBytes() {
      java.lang.Object ref = tipoDemanda_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipoDemanda_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRECIO_FIELD_NUMBER = 2;
    private double precio_;
    /**
     * <code>double precio = 2;</code>
     */
    public double getPrecio() {
      return precio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTipoDemandaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tipoDemanda_);
      }
      if (precio_ != 0D) {
        output.writeDouble(2, precio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTipoDemandaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tipoDemanda_);
      }
      if (precio_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, precio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.ActualizarPreciosProto.ActualizarReply)) {
        return super.equals(obj);
      }
      grpc.ActualizarPreciosProto.ActualizarReply other = (grpc.ActualizarPreciosProto.ActualizarReply) obj;

      boolean result = true;
      result = result && getTipoDemanda()
          .equals(other.getTipoDemanda());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrecio())
          == java.lang.Double.doubleToLongBits(
              other.getPrecio()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPODEMANDA_FIELD_NUMBER;
      hash = (53 * hash) + getTipoDemanda().hashCode();
      hash = (37 * hash) + PRECIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrecio()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.ActualizarPreciosProto.ActualizarReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.ActualizarPreciosProto.ActualizarReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActualizarReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActualizarReply)
        grpc.ActualizarPreciosProto.ActualizarReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.ActualizarPreciosProto.ActualizarReply.class, grpc.ActualizarPreciosProto.ActualizarReply.Builder.class);
      }

      // Construct using grpc.ActualizarPreciosProto.ActualizarReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tipoDemanda_ = "";

        precio_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.ActualizarPreciosProto.internal_static_ActualizarReply_descriptor;
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarReply getDefaultInstanceForType() {
        return grpc.ActualizarPreciosProto.ActualizarReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarReply build() {
        grpc.ActualizarPreciosProto.ActualizarReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.ActualizarPreciosProto.ActualizarReply buildPartial() {
        grpc.ActualizarPreciosProto.ActualizarReply result = new grpc.ActualizarPreciosProto.ActualizarReply(this);
        result.tipoDemanda_ = tipoDemanda_;
        result.precio_ = precio_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.ActualizarPreciosProto.ActualizarReply) {
          return mergeFrom((grpc.ActualizarPreciosProto.ActualizarReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.ActualizarPreciosProto.ActualizarReply other) {
        if (other == grpc.ActualizarPreciosProto.ActualizarReply.getDefaultInstance()) return this;
        if (!other.getTipoDemanda().isEmpty()) {
          tipoDemanda_ = other.tipoDemanda_;
          onChanged();
        }
        if (other.getPrecio() != 0D) {
          setPrecio(other.getPrecio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.ActualizarPreciosProto.ActualizarReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.ActualizarPreciosProto.ActualizarReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tipoDemanda_ = "";
      /**
       * <code>string tipoDemanda = 1;</code>
       */
      public java.lang.String getTipoDemanda() {
        java.lang.Object ref = tipoDemanda_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipoDemanda_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tipoDemanda = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTipoDemandaBytes() {
        java.lang.Object ref = tipoDemanda_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipoDemanda_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tipoDemanda = 1;</code>
       */
      public Builder setTipoDemanda(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipoDemanda_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tipoDemanda = 1;</code>
       */
      public Builder clearTipoDemanda() {
        
        tipoDemanda_ = getDefaultInstance().getTipoDemanda();
        onChanged();
        return this;
      }
      /**
       * <code>string tipoDemanda = 1;</code>
       */
      public Builder setTipoDemandaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipoDemanda_ = value;
        onChanged();
        return this;
      }

      private double precio_ ;
      /**
       * <code>double precio = 2;</code>
       */
      public double getPrecio() {
        return precio_;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder setPrecio(double value) {
        
        precio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder clearPrecio() {
        
        precio_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActualizarReply)
    }

    // @@protoc_insertion_point(class_scope:ActualizarReply)
    private static final grpc.ActualizarPreciosProto.ActualizarReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.ActualizarPreciosProto.ActualizarReply();
    }

    public static grpc.ActualizarPreciosProto.ActualizarReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActualizarReply>
        PARSER = new com.google.protobuf.AbstractParser<ActualizarReply>() {
      @java.lang.Override
      public ActualizarReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActualizarReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActualizarReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActualizarReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.ActualizarPreciosProto.ActualizarReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActualizarRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActualizarRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActualizarReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActualizarReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ActualizarPrecios.proto\"?\n\021ActualizarR" +
      "equest\022\013\n\003NIF\030\001 \001(\t\022\021\n\tApellidos\030\002 \001(\t\022\n" +
      "\n\002IP\030\003 \001(\t\"6\n\017ActualizarReply\022\023\n\013tipoDem" +
      "anda\030\001 \001(\t\022\016\n\006precio\030\002 \001(\0012P\n\021Actualizar" +
      "Precios\022;\n\021actualizarPrecios\022\022.Actualiza" +
      "rRequest\032\020.ActualizarReply0\001B\036\n\004grpcB\026Ac" +
      "tualizarPreciosProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ActualizarRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ActualizarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActualizarRequest_descriptor,
        new java.lang.String[] { "NIF", "Apellidos", "IP", });
    internal_static_ActualizarReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ActualizarReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActualizarReply_descriptor,
        new java.lang.String[] { "TipoDemanda", "Precio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
