// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditoria.proto

package grpc;

public final class AuditoriaOuterClass {
  private AuditoriaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuditoriaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuditoriaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double limiteKwh = 1;</code>
     */
    double getLimiteKwh();
  }
  /**
   * Protobuf type {@code AuditoriaRequest}
   */
  public  static final class AuditoriaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuditoriaRequest)
      AuditoriaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuditoriaRequest.newBuilder() to construct.
    private AuditoriaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuditoriaRequest() {
      limiteKwh_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuditoriaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              limiteKwh_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.AuditoriaOuterClass.internal_static_AuditoriaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.AuditoriaOuterClass.internal_static_AuditoriaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.AuditoriaOuterClass.AuditoriaRequest.class, grpc.AuditoriaOuterClass.AuditoriaRequest.Builder.class);
    }

    public static final int LIMITEKWH_FIELD_NUMBER = 1;
    private double limiteKwh_;
    /**
     * <code>double limiteKwh = 1;</code>
     */
    public double getLimiteKwh() {
      return limiteKwh_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (limiteKwh_ != 0D) {
        output.writeDouble(1, limiteKwh_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (limiteKwh_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, limiteKwh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.AuditoriaOuterClass.AuditoriaRequest)) {
        return super.equals(obj);
      }
      grpc.AuditoriaOuterClass.AuditoriaRequest other = (grpc.AuditoriaOuterClass.AuditoriaRequest) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getLimiteKwh())
          == java.lang.Double.doubleToLongBits(
              other.getLimiteKwh()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIMITEKWH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLimiteKwh()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.AuditoriaOuterClass.AuditoriaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuditoriaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuditoriaRequest)
        grpc.AuditoriaOuterClass.AuditoriaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.AuditoriaOuterClass.AuditoriaRequest.class, grpc.AuditoriaOuterClass.AuditoriaRequest.Builder.class);
      }

      // Construct using grpc.AuditoriaOuterClass.AuditoriaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        limiteKwh_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaRequest_descriptor;
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaRequest getDefaultInstanceForType() {
        return grpc.AuditoriaOuterClass.AuditoriaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaRequest build() {
        grpc.AuditoriaOuterClass.AuditoriaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaRequest buildPartial() {
        grpc.AuditoriaOuterClass.AuditoriaRequest result = new grpc.AuditoriaOuterClass.AuditoriaRequest(this);
        result.limiteKwh_ = limiteKwh_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.AuditoriaOuterClass.AuditoriaRequest) {
          return mergeFrom((grpc.AuditoriaOuterClass.AuditoriaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.AuditoriaOuterClass.AuditoriaRequest other) {
        if (other == grpc.AuditoriaOuterClass.AuditoriaRequest.getDefaultInstance()) return this;
        if (other.getLimiteKwh() != 0D) {
          setLimiteKwh(other.getLimiteKwh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.AuditoriaOuterClass.AuditoriaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.AuditoriaOuterClass.AuditoriaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double limiteKwh_ ;
      /**
       * <code>double limiteKwh = 1;</code>
       */
      public double getLimiteKwh() {
        return limiteKwh_;
      }
      /**
       * <code>double limiteKwh = 1;</code>
       */
      public Builder setLimiteKwh(double value) {
        
        limiteKwh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double limiteKwh = 1;</code>
       */
      public Builder clearLimiteKwh() {
        
        limiteKwh_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuditoriaRequest)
    }

    // @@protoc_insertion_point(class_scope:AuditoriaRequest)
    private static final grpc.AuditoriaOuterClass.AuditoriaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.AuditoriaOuterClass.AuditoriaRequest();
    }

    public static grpc.AuditoriaOuterClass.AuditoriaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuditoriaRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuditoriaRequest>() {
      @java.lang.Override
      public AuditoriaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuditoriaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuditoriaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuditoriaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.AuditoriaOuterClass.AuditoriaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuditoriaReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuditoriaReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idConsumo = 1;</code>
     */
    java.lang.String getIdConsumo();
    /**
     * <code>string idConsumo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdConsumoBytes();

    /**
     * <code>int32 zona = 2;</code>
     */
    int getZona();

    /**
     * <code>double kwh = 3;</code>
     */
    double getKwh();
  }
  /**
   * Protobuf type {@code AuditoriaReply}
   */
  public  static final class AuditoriaReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuditoriaReply)
      AuditoriaReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuditoriaReply.newBuilder() to construct.
    private AuditoriaReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuditoriaReply() {
      idConsumo_ = "";
      zona_ = 0;
      kwh_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuditoriaReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idConsumo_ = s;
              break;
            }
            case 16: {

              zona_ = input.readInt32();
              break;
            }
            case 25: {

              kwh_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.AuditoriaOuterClass.internal_static_AuditoriaReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.AuditoriaOuterClass.internal_static_AuditoriaReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.AuditoriaOuterClass.AuditoriaReply.class, grpc.AuditoriaOuterClass.AuditoriaReply.Builder.class);
    }

    public static final int IDCONSUMO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idConsumo_;
    /**
     * <code>string idConsumo = 1;</code>
     */
    public java.lang.String getIdConsumo() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idConsumo_ = s;
        return s;
      }
    }
    /**
     * <code>string idConsumo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdConsumoBytes() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idConsumo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZONA_FIELD_NUMBER = 2;
    private int zona_;
    /**
     * <code>int32 zona = 2;</code>
     */
    public int getZona() {
      return zona_;
    }

    public static final int KWH_FIELD_NUMBER = 3;
    private double kwh_;
    /**
     * <code>double kwh = 3;</code>
     */
    public double getKwh() {
      return kwh_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdConsumoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idConsumo_);
      }
      if (zona_ != 0) {
        output.writeInt32(2, zona_);
      }
      if (kwh_ != 0D) {
        output.writeDouble(3, kwh_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdConsumoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idConsumo_);
      }
      if (zona_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, zona_);
      }
      if (kwh_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, kwh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.AuditoriaOuterClass.AuditoriaReply)) {
        return super.equals(obj);
      }
      grpc.AuditoriaOuterClass.AuditoriaReply other = (grpc.AuditoriaOuterClass.AuditoriaReply) obj;

      boolean result = true;
      result = result && getIdConsumo()
          .equals(other.getIdConsumo());
      result = result && (getZona()
          == other.getZona());
      result = result && (
          java.lang.Double.doubleToLongBits(getKwh())
          == java.lang.Double.doubleToLongBits(
              other.getKwh()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCONSUMO_FIELD_NUMBER;
      hash = (53 * hash) + getIdConsumo().hashCode();
      hash = (37 * hash) + ZONA_FIELD_NUMBER;
      hash = (53 * hash) + getZona();
      hash = (37 * hash) + KWH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKwh()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.AuditoriaOuterClass.AuditoriaReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.AuditoriaOuterClass.AuditoriaReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuditoriaReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuditoriaReply)
        grpc.AuditoriaOuterClass.AuditoriaReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.AuditoriaOuterClass.AuditoriaReply.class, grpc.AuditoriaOuterClass.AuditoriaReply.Builder.class);
      }

      // Construct using grpc.AuditoriaOuterClass.AuditoriaReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idConsumo_ = "";

        zona_ = 0;

        kwh_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.AuditoriaOuterClass.internal_static_AuditoriaReply_descriptor;
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaReply getDefaultInstanceForType() {
        return grpc.AuditoriaOuterClass.AuditoriaReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaReply build() {
        grpc.AuditoriaOuterClass.AuditoriaReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.AuditoriaOuterClass.AuditoriaReply buildPartial() {
        grpc.AuditoriaOuterClass.AuditoriaReply result = new grpc.AuditoriaOuterClass.AuditoriaReply(this);
        result.idConsumo_ = idConsumo_;
        result.zona_ = zona_;
        result.kwh_ = kwh_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.AuditoriaOuterClass.AuditoriaReply) {
          return mergeFrom((grpc.AuditoriaOuterClass.AuditoriaReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.AuditoriaOuterClass.AuditoriaReply other) {
        if (other == grpc.AuditoriaOuterClass.AuditoriaReply.getDefaultInstance()) return this;
        if (!other.getIdConsumo().isEmpty()) {
          idConsumo_ = other.idConsumo_;
          onChanged();
        }
        if (other.getZona() != 0) {
          setZona(other.getZona());
        }
        if (other.getKwh() != 0D) {
          setKwh(other.getKwh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.AuditoriaOuterClass.AuditoriaReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.AuditoriaOuterClass.AuditoriaReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idConsumo_ = "";
      /**
       * <code>string idConsumo = 1;</code>
       */
      public java.lang.String getIdConsumo() {
        java.lang.Object ref = idConsumo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idConsumo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdConsumoBytes() {
        java.lang.Object ref = idConsumo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idConsumo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idConsumo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder clearIdConsumo() {
        
        idConsumo_ = getDefaultInstance().getIdConsumo();
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idConsumo_ = value;
        onChanged();
        return this;
      }

      private int zona_ ;
      /**
       * <code>int32 zona = 2;</code>
       */
      public int getZona() {
        return zona_;
      }
      /**
       * <code>int32 zona = 2;</code>
       */
      public Builder setZona(int value) {
        
        zona_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 zona = 2;</code>
       */
      public Builder clearZona() {
        
        zona_ = 0;
        onChanged();
        return this;
      }

      private double kwh_ ;
      /**
       * <code>double kwh = 3;</code>
       */
      public double getKwh() {
        return kwh_;
      }
      /**
       * <code>double kwh = 3;</code>
       */
      public Builder setKwh(double value) {
        
        kwh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double kwh = 3;</code>
       */
      public Builder clearKwh() {
        
        kwh_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuditoriaReply)
    }

    // @@protoc_insertion_point(class_scope:AuditoriaReply)
    private static final grpc.AuditoriaOuterClass.AuditoriaReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.AuditoriaOuterClass.AuditoriaReply();
    }

    public static grpc.AuditoriaOuterClass.AuditoriaReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuditoriaReply>
        PARSER = new com.google.protobuf.AbstractParser<AuditoriaReply>() {
      @java.lang.Override
      public AuditoriaReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuditoriaReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuditoriaReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuditoriaReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.AuditoriaOuterClass.AuditoriaReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuditoriaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuditoriaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuditoriaReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuditoriaReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017auditoria.proto\"%\n\020AuditoriaRequest\022\021\n" +
      "\tlimiteKwh\030\001 \001(\001\">\n\016AuditoriaReply\022\021\n\tid" +
      "Consumo\030\001 \001(\t\022\014\n\004zona\030\002 \001(\005\022\013\n\003kwh\030\003 \001(\001" +
      "2U\n\020GestorAuditorias\022A\n\031obtenerConsumosP" +
      "eligrosos\022\021.AuditoriaRequest\032\017.Auditoria" +
      "Reply0\001B\033\n\004grpcB\023AuditoriaOuterClassb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AuditoriaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuditoriaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuditoriaRequest_descriptor,
        new java.lang.String[] { "LimiteKwh", });
    internal_static_AuditoriaReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuditoriaReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuditoriaReply_descriptor,
        new java.lang.String[] { "IdConsumo", "Zona", "Kwh", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
