// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filtro.proto

package grpc;

public final class FiltroOuterClass {
  private FiltroOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FiltroRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FiltroRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idConsumo = 1;</code>
     */
    java.lang.String getIdConsumo();
    /**
     * <code>string idConsumo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdConsumoBytes();

    /**
     * <code>string direccion = 2;</code>
     */
    java.lang.String getDireccion();
    /**
     * <code>string direccion = 2;</code>
     */
    com.google.protobuf.ByteString
        getDireccionBytes();

    /**
     * <code>int32 totalKWh = 3;</code>
     */
    int getTotalKWh();
  }
  /**
   * Protobuf type {@code FiltroRequest}
   */
  public  static final class FiltroRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FiltroRequest)
      FiltroRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FiltroRequest.newBuilder() to construct.
    private FiltroRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FiltroRequest() {
      idConsumo_ = "";
      direccion_ = "";
      totalKWh_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FiltroRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idConsumo_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              direccion_ = s;
              break;
            }
            case 24: {

              totalKWh_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.FiltroOuterClass.internal_static_FiltroRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.FiltroOuterClass.internal_static_FiltroRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.FiltroOuterClass.FiltroRequest.class, grpc.FiltroOuterClass.FiltroRequest.Builder.class);
    }

    public static final int IDCONSUMO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idConsumo_;
    /**
     * <code>string idConsumo = 1;</code>
     */
    public java.lang.String getIdConsumo() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idConsumo_ = s;
        return s;
      }
    }
    /**
     * <code>string idConsumo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdConsumoBytes() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idConsumo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECCION_FIELD_NUMBER = 2;
    private volatile java.lang.Object direccion_;
    /**
     * <code>string direccion = 2;</code>
     */
    public java.lang.String getDireccion() {
      java.lang.Object ref = direccion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direccion_ = s;
        return s;
      }
    }
    /**
     * <code>string direccion = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDireccionBytes() {
      java.lang.Object ref = direccion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direccion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALKWH_FIELD_NUMBER = 3;
    private int totalKWh_;
    /**
     * <code>int32 totalKWh = 3;</code>
     */
    public int getTotalKWh() {
      return totalKWh_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdConsumoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idConsumo_);
      }
      if (!getDireccionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, direccion_);
      }
      if (totalKWh_ != 0) {
        output.writeInt32(3, totalKWh_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdConsumoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idConsumo_);
      }
      if (!getDireccionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, direccion_);
      }
      if (totalKWh_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalKWh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.FiltroOuterClass.FiltroRequest)) {
        return super.equals(obj);
      }
      grpc.FiltroOuterClass.FiltroRequest other = (grpc.FiltroOuterClass.FiltroRequest) obj;

      boolean result = true;
      result = result && getIdConsumo()
          .equals(other.getIdConsumo());
      result = result && getDireccion()
          .equals(other.getDireccion());
      result = result && (getTotalKWh()
          == other.getTotalKWh());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCONSUMO_FIELD_NUMBER;
      hash = (53 * hash) + getIdConsumo().hashCode();
      hash = (37 * hash) + DIRECCION_FIELD_NUMBER;
      hash = (53 * hash) + getDireccion().hashCode();
      hash = (37 * hash) + TOTALKWH_FIELD_NUMBER;
      hash = (53 * hash) + getTotalKWh();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.FiltroOuterClass.FiltroRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FiltroRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FiltroRequest)
        grpc.FiltroOuterClass.FiltroRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.FiltroOuterClass.internal_static_FiltroRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.FiltroOuterClass.internal_static_FiltroRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.FiltroOuterClass.FiltroRequest.class, grpc.FiltroOuterClass.FiltroRequest.Builder.class);
      }

      // Construct using grpc.FiltroOuterClass.FiltroRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idConsumo_ = "";

        direccion_ = "";

        totalKWh_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.FiltroOuterClass.internal_static_FiltroRequest_descriptor;
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroRequest getDefaultInstanceForType() {
        return grpc.FiltroOuterClass.FiltroRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroRequest build() {
        grpc.FiltroOuterClass.FiltroRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroRequest buildPartial() {
        grpc.FiltroOuterClass.FiltroRequest result = new grpc.FiltroOuterClass.FiltroRequest(this);
        result.idConsumo_ = idConsumo_;
        result.direccion_ = direccion_;
        result.totalKWh_ = totalKWh_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.FiltroOuterClass.FiltroRequest) {
          return mergeFrom((grpc.FiltroOuterClass.FiltroRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.FiltroOuterClass.FiltroRequest other) {
        if (other == grpc.FiltroOuterClass.FiltroRequest.getDefaultInstance()) return this;
        if (!other.getIdConsumo().isEmpty()) {
          idConsumo_ = other.idConsumo_;
          onChanged();
        }
        if (!other.getDireccion().isEmpty()) {
          direccion_ = other.direccion_;
          onChanged();
        }
        if (other.getTotalKWh() != 0) {
          setTotalKWh(other.getTotalKWh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.FiltroOuterClass.FiltroRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.FiltroOuterClass.FiltroRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idConsumo_ = "";
      /**
       * <code>string idConsumo = 1;</code>
       */
      public java.lang.String getIdConsumo() {
        java.lang.Object ref = idConsumo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idConsumo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdConsumoBytes() {
        java.lang.Object ref = idConsumo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idConsumo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idConsumo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder clearIdConsumo() {
        
        idConsumo_ = getDefaultInstance().getIdConsumo();
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idConsumo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object direccion_ = "";
      /**
       * <code>string direccion = 2;</code>
       */
      public java.lang.String getDireccion() {
        java.lang.Object ref = direccion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direccion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direccion = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDireccionBytes() {
        java.lang.Object ref = direccion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direccion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direccion = 2;</code>
       */
      public Builder setDireccion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direccion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direccion = 2;</code>
       */
      public Builder clearDireccion() {
        
        direccion_ = getDefaultInstance().getDireccion();
        onChanged();
        return this;
      }
      /**
       * <code>string direccion = 2;</code>
       */
      public Builder setDireccionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direccion_ = value;
        onChanged();
        return this;
      }

      private int totalKWh_ ;
      /**
       * <code>int32 totalKWh = 3;</code>
       */
      public int getTotalKWh() {
        return totalKWh_;
      }
      /**
       * <code>int32 totalKWh = 3;</code>
       */
      public Builder setTotalKWh(int value) {
        
        totalKWh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalKWh = 3;</code>
       */
      public Builder clearTotalKWh() {
        
        totalKWh_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FiltroRequest)
    }

    // @@protoc_insertion_point(class_scope:FiltroRequest)
    private static final grpc.FiltroOuterClass.FiltroRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.FiltroOuterClass.FiltroRequest();
    }

    public static grpc.FiltroOuterClass.FiltroRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FiltroRequest>
        PARSER = new com.google.protobuf.AbstractParser<FiltroRequest>() {
      @java.lang.Override
      public FiltroRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FiltroRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FiltroRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FiltroRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.FiltroOuterClass.FiltroRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FiltroReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FiltroReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idConsumo = 1;</code>
     */
    java.lang.String getIdConsumo();
    /**
     * <code>string idConsumo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdConsumoBytes();

    /**
     * <code>int32 totalKWh = 2;</code>
     */
    int getTotalKWh();
  }
  /**
   * Protobuf type {@code FiltroReply}
   */
  public  static final class FiltroReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FiltroReply)
      FiltroReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FiltroReply.newBuilder() to construct.
    private FiltroReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FiltroReply() {
      idConsumo_ = "";
      totalKWh_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FiltroReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idConsumo_ = s;
              break;
            }
            case 16: {

              totalKWh_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.FiltroOuterClass.internal_static_FiltroReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.FiltroOuterClass.internal_static_FiltroReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.FiltroOuterClass.FiltroReply.class, grpc.FiltroOuterClass.FiltroReply.Builder.class);
    }

    public static final int IDCONSUMO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idConsumo_;
    /**
     * <code>string idConsumo = 1;</code>
     */
    public java.lang.String getIdConsumo() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idConsumo_ = s;
        return s;
      }
    }
    /**
     * <code>string idConsumo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdConsumoBytes() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idConsumo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTALKWH_FIELD_NUMBER = 2;
    private int totalKWh_;
    /**
     * <code>int32 totalKWh = 2;</code>
     */
    public int getTotalKWh() {
      return totalKWh_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdConsumoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idConsumo_);
      }
      if (totalKWh_ != 0) {
        output.writeInt32(2, totalKWh_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdConsumoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idConsumo_);
      }
      if (totalKWh_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalKWh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.FiltroOuterClass.FiltroReply)) {
        return super.equals(obj);
      }
      grpc.FiltroOuterClass.FiltroReply other = (grpc.FiltroOuterClass.FiltroReply) obj;

      boolean result = true;
      result = result && getIdConsumo()
          .equals(other.getIdConsumo());
      result = result && (getTotalKWh()
          == other.getTotalKWh());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCONSUMO_FIELD_NUMBER;
      hash = (53 * hash) + getIdConsumo().hashCode();
      hash = (37 * hash) + TOTALKWH_FIELD_NUMBER;
      hash = (53 * hash) + getTotalKWh();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.FiltroOuterClass.FiltroReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.FiltroOuterClass.FiltroReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FiltroReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FiltroReply)
        grpc.FiltroOuterClass.FiltroReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.FiltroOuterClass.internal_static_FiltroReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.FiltroOuterClass.internal_static_FiltroReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.FiltroOuterClass.FiltroReply.class, grpc.FiltroOuterClass.FiltroReply.Builder.class);
      }

      // Construct using grpc.FiltroOuterClass.FiltroReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idConsumo_ = "";

        totalKWh_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.FiltroOuterClass.internal_static_FiltroReply_descriptor;
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroReply getDefaultInstanceForType() {
        return grpc.FiltroOuterClass.FiltroReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroReply build() {
        grpc.FiltroOuterClass.FiltroReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.FiltroOuterClass.FiltroReply buildPartial() {
        grpc.FiltroOuterClass.FiltroReply result = new grpc.FiltroOuterClass.FiltroReply(this);
        result.idConsumo_ = idConsumo_;
        result.totalKWh_ = totalKWh_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.FiltroOuterClass.FiltroReply) {
          return mergeFrom((grpc.FiltroOuterClass.FiltroReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.FiltroOuterClass.FiltroReply other) {
        if (other == grpc.FiltroOuterClass.FiltroReply.getDefaultInstance()) return this;
        if (!other.getIdConsumo().isEmpty()) {
          idConsumo_ = other.idConsumo_;
          onChanged();
        }
        if (other.getTotalKWh() != 0) {
          setTotalKWh(other.getTotalKWh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.FiltroOuterClass.FiltroReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.FiltroOuterClass.FiltroReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idConsumo_ = "";
      /**
       * <code>string idConsumo = 1;</code>
       */
      public java.lang.String getIdConsumo() {
        java.lang.Object ref = idConsumo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idConsumo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdConsumoBytes() {
        java.lang.Object ref = idConsumo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idConsumo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idConsumo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder clearIdConsumo() {
        
        idConsumo_ = getDefaultInstance().getIdConsumo();
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idConsumo_ = value;
        onChanged();
        return this;
      }

      private int totalKWh_ ;
      /**
       * <code>int32 totalKWh = 2;</code>
       */
      public int getTotalKWh() {
        return totalKWh_;
      }
      /**
       * <code>int32 totalKWh = 2;</code>
       */
      public Builder setTotalKWh(int value) {
        
        totalKWh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalKWh = 2;</code>
       */
      public Builder clearTotalKWh() {
        
        totalKWh_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FiltroReply)
    }

    // @@protoc_insertion_point(class_scope:FiltroReply)
    private static final grpc.FiltroOuterClass.FiltroReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.FiltroOuterClass.FiltroReply();
    }

    public static grpc.FiltroOuterClass.FiltroReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FiltroReply>
        PARSER = new com.google.protobuf.AbstractParser<FiltroReply>() {
      @java.lang.Override
      public FiltroReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FiltroReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FiltroReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FiltroReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.FiltroOuterClass.FiltroReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FiltroRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FiltroRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FiltroReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FiltroReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014filtro.proto\"G\n\rFiltroRequest\022\021\n\tidCon" +
      "sumo\030\001 \001(\t\022\021\n\tdireccion\030\002 \001(\t\022\020\n\010totalKW" +
      "h\030\003 \001(\005\"2\n\013FiltroReply\022\021\n\tidConsumo\030\001 \001(" +
      "\t\022\020\n\010totalKWh\030\002 \001(\00529\n\010Filtrado\022-\n\007filtr" +
      "ar\022\016.FiltroRequest\032\014.FiltroReply\"\000(\0010\001B\030" +
      "\n\004grpcB\020FiltroOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FiltroRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FiltroRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FiltroRequest_descriptor,
        new java.lang.String[] { "IdConsumo", "Direccion", "TotalKWh", });
    internal_static_FiltroReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FiltroReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FiltroReply_descriptor,
        new java.lang.String[] { "IdConsumo", "TotalKWh", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
