// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: precios.proto

package grpc;

public final class PreciosProto {
  private PreciosProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PreciosRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PreciosRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idConsumo = 1;</code>
     */
    java.lang.String getIdConsumo();
    /**
     * <code>string idConsumo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdConsumoBytes();

    /**
     * <code>int32 idZona = 2;</code>
     */
    int getIdZona();

    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    java.util.List<grpc.PreciosProto.DemandaRequest> 
        getDemandasList();
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    grpc.PreciosProto.DemandaRequest getDemandas(int index);
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    int getDemandasCount();
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    java.util.List<? extends grpc.PreciosProto.DemandaRequestOrBuilder> 
        getDemandasOrBuilderList();
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    grpc.PreciosProto.DemandaRequestOrBuilder getDemandasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PreciosRequest}
   */
  public  static final class PreciosRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PreciosRequest)
      PreciosRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreciosRequest.newBuilder() to construct.
    private PreciosRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreciosRequest() {
      idConsumo_ = "";
      idZona_ = 0;
      demandas_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreciosRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idConsumo_ = s;
              break;
            }
            case 16: {

              idZona_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                demandas_ = new java.util.ArrayList<grpc.PreciosProto.DemandaRequest>();
                mutable_bitField0_ |= 0x00000004;
              }
              demandas_.add(
                  input.readMessage(grpc.PreciosProto.DemandaRequest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          demandas_ = java.util.Collections.unmodifiableList(demandas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.PreciosProto.internal_static_PreciosRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.PreciosProto.internal_static_PreciosRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.PreciosProto.PreciosRequest.class, grpc.PreciosProto.PreciosRequest.Builder.class);
    }

    private int bitField0_;
    public static final int IDCONSUMO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idConsumo_;
    /**
     * <code>string idConsumo = 1;</code>
     */
    public java.lang.String getIdConsumo() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idConsumo_ = s;
        return s;
      }
    }
    /**
     * <code>string idConsumo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdConsumoBytes() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idConsumo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDZONA_FIELD_NUMBER = 2;
    private int idZona_;
    /**
     * <code>int32 idZona = 2;</code>
     */
    public int getIdZona() {
      return idZona_;
    }

    public static final int DEMANDAS_FIELD_NUMBER = 3;
    private java.util.List<grpc.PreciosProto.DemandaRequest> demandas_;
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    public java.util.List<grpc.PreciosProto.DemandaRequest> getDemandasList() {
      return demandas_;
    }
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    public java.util.List<? extends grpc.PreciosProto.DemandaRequestOrBuilder> 
        getDemandasOrBuilderList() {
      return demandas_;
    }
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    public int getDemandasCount() {
      return demandas_.size();
    }
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    public grpc.PreciosProto.DemandaRequest getDemandas(int index) {
      return demandas_.get(index);
    }
    /**
     * <code>repeated .DemandaRequest demandas = 3;</code>
     */
    public grpc.PreciosProto.DemandaRequestOrBuilder getDemandasOrBuilder(
        int index) {
      return demandas_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdConsumoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idConsumo_);
      }
      if (idZona_ != 0) {
        output.writeInt32(2, idZona_);
      }
      for (int i = 0; i < demandas_.size(); i++) {
        output.writeMessage(3, demandas_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdConsumoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idConsumo_);
      }
      if (idZona_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, idZona_);
      }
      for (int i = 0; i < demandas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, demandas_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.PreciosProto.PreciosRequest)) {
        return super.equals(obj);
      }
      grpc.PreciosProto.PreciosRequest other = (grpc.PreciosProto.PreciosRequest) obj;

      boolean result = true;
      result = result && getIdConsumo()
          .equals(other.getIdConsumo());
      result = result && (getIdZona()
          == other.getIdZona());
      result = result && getDemandasList()
          .equals(other.getDemandasList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCONSUMO_FIELD_NUMBER;
      hash = (53 * hash) + getIdConsumo().hashCode();
      hash = (37 * hash) + IDZONA_FIELD_NUMBER;
      hash = (53 * hash) + getIdZona();
      if (getDemandasCount() > 0) {
        hash = (37 * hash) + DEMANDAS_FIELD_NUMBER;
        hash = (53 * hash) + getDemandasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.PreciosProto.PreciosRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.PreciosProto.PreciosRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PreciosRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PreciosRequest)
        grpc.PreciosProto.PreciosRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.PreciosProto.internal_static_PreciosRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.PreciosProto.internal_static_PreciosRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.PreciosProto.PreciosRequest.class, grpc.PreciosProto.PreciosRequest.Builder.class);
      }

      // Construct using grpc.PreciosProto.PreciosRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDemandasFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idConsumo_ = "";

        idZona_ = 0;

        if (demandasBuilder_ == null) {
          demandas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          demandasBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.PreciosProto.internal_static_PreciosRequest_descriptor;
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosRequest getDefaultInstanceForType() {
        return grpc.PreciosProto.PreciosRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosRequest build() {
        grpc.PreciosProto.PreciosRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosRequest buildPartial() {
        grpc.PreciosProto.PreciosRequest result = new grpc.PreciosProto.PreciosRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.idConsumo_ = idConsumo_;
        result.idZona_ = idZona_;
        if (demandasBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            demandas_ = java.util.Collections.unmodifiableList(demandas_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.demandas_ = demandas_;
        } else {
          result.demandas_ = demandasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.PreciosProto.PreciosRequest) {
          return mergeFrom((grpc.PreciosProto.PreciosRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.PreciosProto.PreciosRequest other) {
        if (other == grpc.PreciosProto.PreciosRequest.getDefaultInstance()) return this;
        if (!other.getIdConsumo().isEmpty()) {
          idConsumo_ = other.idConsumo_;
          onChanged();
        }
        if (other.getIdZona() != 0) {
          setIdZona(other.getIdZona());
        }
        if (demandasBuilder_ == null) {
          if (!other.demandas_.isEmpty()) {
            if (demandas_.isEmpty()) {
              demandas_ = other.demandas_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDemandasIsMutable();
              demandas_.addAll(other.demandas_);
            }
            onChanged();
          }
        } else {
          if (!other.demandas_.isEmpty()) {
            if (demandasBuilder_.isEmpty()) {
              demandasBuilder_.dispose();
              demandasBuilder_ = null;
              demandas_ = other.demandas_;
              bitField0_ = (bitField0_ & ~0x00000004);
              demandasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDemandasFieldBuilder() : null;
            } else {
              demandasBuilder_.addAllMessages(other.demandas_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.PreciosProto.PreciosRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.PreciosProto.PreciosRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object idConsumo_ = "";
      /**
       * <code>string idConsumo = 1;</code>
       */
      public java.lang.String getIdConsumo() {
        java.lang.Object ref = idConsumo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idConsumo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdConsumoBytes() {
        java.lang.Object ref = idConsumo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idConsumo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idConsumo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder clearIdConsumo() {
        
        idConsumo_ = getDefaultInstance().getIdConsumo();
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idConsumo_ = value;
        onChanged();
        return this;
      }

      private int idZona_ ;
      /**
       * <code>int32 idZona = 2;</code>
       */
      public int getIdZona() {
        return idZona_;
      }
      /**
       * <code>int32 idZona = 2;</code>
       */
      public Builder setIdZona(int value) {
        
        idZona_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idZona = 2;</code>
       */
      public Builder clearIdZona() {
        
        idZona_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<grpc.PreciosProto.DemandaRequest> demandas_ =
        java.util.Collections.emptyList();
      private void ensureDemandasIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          demandas_ = new java.util.ArrayList<grpc.PreciosProto.DemandaRequest>(demandas_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.PreciosProto.DemandaRequest, grpc.PreciosProto.DemandaRequest.Builder, grpc.PreciosProto.DemandaRequestOrBuilder> demandasBuilder_;

      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public java.util.List<grpc.PreciosProto.DemandaRequest> getDemandasList() {
        if (demandasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(demandas_);
        } else {
          return demandasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public int getDemandasCount() {
        if (demandasBuilder_ == null) {
          return demandas_.size();
        } else {
          return demandasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public grpc.PreciosProto.DemandaRequest getDemandas(int index) {
        if (demandasBuilder_ == null) {
          return demandas_.get(index);
        } else {
          return demandasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder setDemandas(
          int index, grpc.PreciosProto.DemandaRequest value) {
        if (demandasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemandasIsMutable();
          demandas_.set(index, value);
          onChanged();
        } else {
          demandasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder setDemandas(
          int index, grpc.PreciosProto.DemandaRequest.Builder builderForValue) {
        if (demandasBuilder_ == null) {
          ensureDemandasIsMutable();
          demandas_.set(index, builderForValue.build());
          onChanged();
        } else {
          demandasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder addDemandas(grpc.PreciosProto.DemandaRequest value) {
        if (demandasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemandasIsMutable();
          demandas_.add(value);
          onChanged();
        } else {
          demandasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder addDemandas(
          int index, grpc.PreciosProto.DemandaRequest value) {
        if (demandasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDemandasIsMutable();
          demandas_.add(index, value);
          onChanged();
        } else {
          demandasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder addDemandas(
          grpc.PreciosProto.DemandaRequest.Builder builderForValue) {
        if (demandasBuilder_ == null) {
          ensureDemandasIsMutable();
          demandas_.add(builderForValue.build());
          onChanged();
        } else {
          demandasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder addDemandas(
          int index, grpc.PreciosProto.DemandaRequest.Builder builderForValue) {
        if (demandasBuilder_ == null) {
          ensureDemandasIsMutable();
          demandas_.add(index, builderForValue.build());
          onChanged();
        } else {
          demandasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder addAllDemandas(
          java.lang.Iterable<? extends grpc.PreciosProto.DemandaRequest> values) {
        if (demandasBuilder_ == null) {
          ensureDemandasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, demandas_);
          onChanged();
        } else {
          demandasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder clearDemandas() {
        if (demandasBuilder_ == null) {
          demandas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          demandasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public Builder removeDemandas(int index) {
        if (demandasBuilder_ == null) {
          ensureDemandasIsMutable();
          demandas_.remove(index);
          onChanged();
        } else {
          demandasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public grpc.PreciosProto.DemandaRequest.Builder getDemandasBuilder(
          int index) {
        return getDemandasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public grpc.PreciosProto.DemandaRequestOrBuilder getDemandasOrBuilder(
          int index) {
        if (demandasBuilder_ == null) {
          return demandas_.get(index);  } else {
          return demandasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public java.util.List<? extends grpc.PreciosProto.DemandaRequestOrBuilder> 
           getDemandasOrBuilderList() {
        if (demandasBuilder_ != null) {
          return demandasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(demandas_);
        }
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public grpc.PreciosProto.DemandaRequest.Builder addDemandasBuilder() {
        return getDemandasFieldBuilder().addBuilder(
            grpc.PreciosProto.DemandaRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public grpc.PreciosProto.DemandaRequest.Builder addDemandasBuilder(
          int index) {
        return getDemandasFieldBuilder().addBuilder(
            index, grpc.PreciosProto.DemandaRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .DemandaRequest demandas = 3;</code>
       */
      public java.util.List<grpc.PreciosProto.DemandaRequest.Builder> 
           getDemandasBuilderList() {
        return getDemandasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.PreciosProto.DemandaRequest, grpc.PreciosProto.DemandaRequest.Builder, grpc.PreciosProto.DemandaRequestOrBuilder> 
          getDemandasFieldBuilder() {
        if (demandasBuilder_ == null) {
          demandasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              grpc.PreciosProto.DemandaRequest, grpc.PreciosProto.DemandaRequest.Builder, grpc.PreciosProto.DemandaRequestOrBuilder>(
                  demandas_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          demandas_ = null;
        }
        return demandasBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PreciosRequest)
    }

    // @@protoc_insertion_point(class_scope:PreciosRequest)
    private static final grpc.PreciosProto.PreciosRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.PreciosProto.PreciosRequest();
    }

    public static grpc.PreciosProto.PreciosRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreciosRequest>
        PARSER = new com.google.protobuf.AbstractParser<PreciosRequest>() {
      @java.lang.Override
      public PreciosRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreciosRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreciosRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreciosRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.PreciosProto.PreciosRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DemandaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DemandaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idTipo = 1;</code>
     */
    java.lang.String getIdTipo();
    /**
     * <code>string idTipo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdTipoBytes();

    /**
     * <code>double KWh = 2;</code>
     */
    double getKWh();

    /**
     * <code>int32 prioridad = 3;</code>
     */
    int getPrioridad();
  }
  /**
   * Protobuf type {@code DemandaRequest}
   */
  public  static final class DemandaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DemandaRequest)
      DemandaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemandaRequest.newBuilder() to construct.
    private DemandaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemandaRequest() {
      idTipo_ = "";
      kWh_ = 0D;
      prioridad_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemandaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idTipo_ = s;
              break;
            }
            case 17: {

              kWh_ = input.readDouble();
              break;
            }
            case 24: {

              prioridad_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.PreciosProto.internal_static_DemandaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.PreciosProto.internal_static_DemandaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.PreciosProto.DemandaRequest.class, grpc.PreciosProto.DemandaRequest.Builder.class);
    }

    public static final int IDTIPO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idTipo_;
    /**
     * <code>string idTipo = 1;</code>
     */
    public java.lang.String getIdTipo() {
      java.lang.Object ref = idTipo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idTipo_ = s;
        return s;
      }
    }
    /**
     * <code>string idTipo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdTipoBytes() {
      java.lang.Object ref = idTipo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idTipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KWH_FIELD_NUMBER = 2;
    private double kWh_;
    /**
     * <code>double KWh = 2;</code>
     */
    public double getKWh() {
      return kWh_;
    }

    public static final int PRIORIDAD_FIELD_NUMBER = 3;
    private int prioridad_;
    /**
     * <code>int32 prioridad = 3;</code>
     */
    public int getPrioridad() {
      return prioridad_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdTipoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idTipo_);
      }
      if (kWh_ != 0D) {
        output.writeDouble(2, kWh_);
      }
      if (prioridad_ != 0) {
        output.writeInt32(3, prioridad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdTipoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idTipo_);
      }
      if (kWh_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, kWh_);
      }
      if (prioridad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, prioridad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.PreciosProto.DemandaRequest)) {
        return super.equals(obj);
      }
      grpc.PreciosProto.DemandaRequest other = (grpc.PreciosProto.DemandaRequest) obj;

      boolean result = true;
      result = result && getIdTipo()
          .equals(other.getIdTipo());
      result = result && (
          java.lang.Double.doubleToLongBits(getKWh())
          == java.lang.Double.doubleToLongBits(
              other.getKWh()));
      result = result && (getPrioridad()
          == other.getPrioridad());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDTIPO_FIELD_NUMBER;
      hash = (53 * hash) + getIdTipo().hashCode();
      hash = (37 * hash) + KWH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKWh()));
      hash = (37 * hash) + PRIORIDAD_FIELD_NUMBER;
      hash = (53 * hash) + getPrioridad();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.PreciosProto.DemandaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.DemandaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.DemandaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.DemandaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.PreciosProto.DemandaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DemandaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DemandaRequest)
        grpc.PreciosProto.DemandaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.PreciosProto.internal_static_DemandaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.PreciosProto.internal_static_DemandaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.PreciosProto.DemandaRequest.class, grpc.PreciosProto.DemandaRequest.Builder.class);
      }

      // Construct using grpc.PreciosProto.DemandaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idTipo_ = "";

        kWh_ = 0D;

        prioridad_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.PreciosProto.internal_static_DemandaRequest_descriptor;
      }

      @java.lang.Override
      public grpc.PreciosProto.DemandaRequest getDefaultInstanceForType() {
        return grpc.PreciosProto.DemandaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.PreciosProto.DemandaRequest build() {
        grpc.PreciosProto.DemandaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.PreciosProto.DemandaRequest buildPartial() {
        grpc.PreciosProto.DemandaRequest result = new grpc.PreciosProto.DemandaRequest(this);
        result.idTipo_ = idTipo_;
        result.kWh_ = kWh_;
        result.prioridad_ = prioridad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.PreciosProto.DemandaRequest) {
          return mergeFrom((grpc.PreciosProto.DemandaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.PreciosProto.DemandaRequest other) {
        if (other == grpc.PreciosProto.DemandaRequest.getDefaultInstance()) return this;
        if (!other.getIdTipo().isEmpty()) {
          idTipo_ = other.idTipo_;
          onChanged();
        }
        if (other.getKWh() != 0D) {
          setKWh(other.getKWh());
        }
        if (other.getPrioridad() != 0) {
          setPrioridad(other.getPrioridad());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.PreciosProto.DemandaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.PreciosProto.DemandaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idTipo_ = "";
      /**
       * <code>string idTipo = 1;</code>
       */
      public java.lang.String getIdTipo() {
        java.lang.Object ref = idTipo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idTipo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idTipo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdTipoBytes() {
        java.lang.Object ref = idTipo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idTipo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idTipo = 1;</code>
       */
      public Builder setIdTipo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idTipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idTipo = 1;</code>
       */
      public Builder clearIdTipo() {
        
        idTipo_ = getDefaultInstance().getIdTipo();
        onChanged();
        return this;
      }
      /**
       * <code>string idTipo = 1;</code>
       */
      public Builder setIdTipoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idTipo_ = value;
        onChanged();
        return this;
      }

      private double kWh_ ;
      /**
       * <code>double KWh = 2;</code>
       */
      public double getKWh() {
        return kWh_;
      }
      /**
       * <code>double KWh = 2;</code>
       */
      public Builder setKWh(double value) {
        
        kWh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double KWh = 2;</code>
       */
      public Builder clearKWh() {
        
        kWh_ = 0D;
        onChanged();
        return this;
      }

      private int prioridad_ ;
      /**
       * <code>int32 prioridad = 3;</code>
       */
      public int getPrioridad() {
        return prioridad_;
      }
      /**
       * <code>int32 prioridad = 3;</code>
       */
      public Builder setPrioridad(int value) {
        
        prioridad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 prioridad = 3;</code>
       */
      public Builder clearPrioridad() {
        
        prioridad_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DemandaRequest)
    }

    // @@protoc_insertion_point(class_scope:DemandaRequest)
    private static final grpc.PreciosProto.DemandaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.PreciosProto.DemandaRequest();
    }

    public static grpc.PreciosProto.DemandaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemandaRequest>
        PARSER = new com.google.protobuf.AbstractParser<DemandaRequest>() {
      @java.lang.Override
      public DemandaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemandaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemandaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemandaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.PreciosProto.DemandaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PreciosReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PreciosReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idConsumo = 1;</code>
     */
    java.lang.String getIdConsumo();
    /**
     * <code>string idConsumo = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdConsumoBytes();

    /**
     * <code>double precio = 2;</code>
     */
    double getPrecio();
  }
  /**
   * Protobuf type {@code PreciosReply}
   */
  public  static final class PreciosReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PreciosReply)
      PreciosReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreciosReply.newBuilder() to construct.
    private PreciosReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreciosReply() {
      idConsumo_ = "";
      precio_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreciosReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              idConsumo_ = s;
              break;
            }
            case 17: {

              precio_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.PreciosProto.internal_static_PreciosReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.PreciosProto.internal_static_PreciosReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.PreciosProto.PreciosReply.class, grpc.PreciosProto.PreciosReply.Builder.class);
    }

    public static final int IDCONSUMO_FIELD_NUMBER = 1;
    private volatile java.lang.Object idConsumo_;
    /**
     * <code>string idConsumo = 1;</code>
     */
    public java.lang.String getIdConsumo() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idConsumo_ = s;
        return s;
      }
    }
    /**
     * <code>string idConsumo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdConsumoBytes() {
      java.lang.Object ref = idConsumo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idConsumo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRECIO_FIELD_NUMBER = 2;
    private double precio_;
    /**
     * <code>double precio = 2;</code>
     */
    public double getPrecio() {
      return precio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdConsumoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idConsumo_);
      }
      if (precio_ != 0D) {
        output.writeDouble(2, precio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdConsumoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idConsumo_);
      }
      if (precio_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, precio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.PreciosProto.PreciosReply)) {
        return super.equals(obj);
      }
      grpc.PreciosProto.PreciosReply other = (grpc.PreciosProto.PreciosReply) obj;

      boolean result = true;
      result = result && getIdConsumo()
          .equals(other.getIdConsumo());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrecio())
          == java.lang.Double.doubleToLongBits(
              other.getPrecio()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCONSUMO_FIELD_NUMBER;
      hash = (53 * hash) + getIdConsumo().hashCode();
      hash = (37 * hash) + PRECIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrecio()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.PreciosProto.PreciosReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.PreciosProto.PreciosReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.PreciosProto.PreciosReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PreciosReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PreciosReply)
        grpc.PreciosProto.PreciosReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.PreciosProto.internal_static_PreciosReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.PreciosProto.internal_static_PreciosReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.PreciosProto.PreciosReply.class, grpc.PreciosProto.PreciosReply.Builder.class);
      }

      // Construct using grpc.PreciosProto.PreciosReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idConsumo_ = "";

        precio_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.PreciosProto.internal_static_PreciosReply_descriptor;
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosReply getDefaultInstanceForType() {
        return grpc.PreciosProto.PreciosReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosReply build() {
        grpc.PreciosProto.PreciosReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.PreciosProto.PreciosReply buildPartial() {
        grpc.PreciosProto.PreciosReply result = new grpc.PreciosProto.PreciosReply(this);
        result.idConsumo_ = idConsumo_;
        result.precio_ = precio_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.PreciosProto.PreciosReply) {
          return mergeFrom((grpc.PreciosProto.PreciosReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.PreciosProto.PreciosReply other) {
        if (other == grpc.PreciosProto.PreciosReply.getDefaultInstance()) return this;
        if (!other.getIdConsumo().isEmpty()) {
          idConsumo_ = other.idConsumo_;
          onChanged();
        }
        if (other.getPrecio() != 0D) {
          setPrecio(other.getPrecio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.PreciosProto.PreciosReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.PreciosProto.PreciosReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object idConsumo_ = "";
      /**
       * <code>string idConsumo = 1;</code>
       */
      public java.lang.String getIdConsumo() {
        java.lang.Object ref = idConsumo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idConsumo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdConsumoBytes() {
        java.lang.Object ref = idConsumo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idConsumo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idConsumo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder clearIdConsumo() {
        
        idConsumo_ = getDefaultInstance().getIdConsumo();
        onChanged();
        return this;
      }
      /**
       * <code>string idConsumo = 1;</code>
       */
      public Builder setIdConsumoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idConsumo_ = value;
        onChanged();
        return this;
      }

      private double precio_ ;
      /**
       * <code>double precio = 2;</code>
       */
      public double getPrecio() {
        return precio_;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder setPrecio(double value) {
        
        precio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double precio = 2;</code>
       */
      public Builder clearPrecio() {
        
        precio_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PreciosReply)
    }

    // @@protoc_insertion_point(class_scope:PreciosReply)
    private static final grpc.PreciosProto.PreciosReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.PreciosProto.PreciosReply();
    }

    public static grpc.PreciosProto.PreciosReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreciosReply>
        PARSER = new com.google.protobuf.AbstractParser<PreciosReply>() {
      @java.lang.Override
      public PreciosReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreciosReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreciosReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreciosReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.PreciosProto.PreciosReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreciosRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreciosRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemandaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DemandaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreciosReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreciosReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprecios.proto\"V\n\016PreciosRequest\022\021\n\tidC" +
      "onsumo\030\001 \001(\t\022\016\n\006idZona\030\002 \001(\005\022!\n\010demandas" +
      "\030\003 \003(\0132\017.DemandaRequest\"@\n\016DemandaReques" +
      "t\022\016\n\006idTipo\030\001 \001(\t\022\013\n\003KWh\030\002 \001(\001\022\021\n\tpriori" +
      "dad\030\003 \001(\005\"1\n\014PreciosReply\022\021\n\tidConsumo\030\001" +
      " \001(\t\022\016\n\006precio\030\002 \001(\0012@\n\007Precios\0225\n\017calcu" +
      "larPrecios\022\017.PreciosRequest\032\r.PreciosRep" +
      "ly(\0010\001B\024\n\004grpcB\014PreciosProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PreciosRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PreciosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreciosRequest_descriptor,
        new java.lang.String[] { "IdConsumo", "IdZona", "Demandas", });
    internal_static_DemandaRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DemandaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DemandaRequest_descriptor,
        new java.lang.String[] { "IdTipo", "KWh", "Prioridad", });
    internal_static_PreciosReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PreciosReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreciosReply_descriptor,
        new java.lang.String[] { "IdConsumo", "Precio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
